Day1/timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'
  get '/contact' => 'site#contact'
  
  #get '/projects' => 'projects#index' 
  #Convención => index para mostar listados
  #
  #get 'projects/:id' => 'projects#show' 
  #Convención => show para mostrar detalle
  #get 'projects/:project_id/entries' => 'entries#index'
  #
  #get 'projects/:project_id/entries/new' => 'entries#new' 
  #Convención => new para crear objetos

  #helper resources y sustituye a todo lo de arriba
  resources :projects, only: [:index, :show] do
  	resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :people, only: [:new, :create, :index, :show, :update, :destroy] 
end

Day1/timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	
	belongs_to :project	

	validates :hours, :minutes, numericality: {only_integer: true}
	validates :date, :hours, :minutes, presence: true
	validates :project_id, presence: true 

end

Day1/timetracking/app/models/participation.rb
class Participation < ActiveRecord::Base

	belongs_to :person
	belongs_to :project
end

Day1/timetracking/app/models/person.rb
class Person < ActiveRecord::Base
	
	has_many :participations
	has_many :projects, through: :participations

	def select_no_associated_project
		Project.all.select do |project|
			!self.projects.find_by(id: project.id)
		end
	end
end

Day1/timetracking/app/models/project.rb
 class Project < ActiveRecord::Base
  
  has_many :entries
  has_many :participations
  has_many :people, through: :participations

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: {maximum: 30}
  validates :name, format: {with: /\A[A-Za-zÑñ0-9\s]+\z/}

	def self.iron_find(params)
		where(id: params).first
	end

	def self.clean_old
    date = Time.now.midnight - 1.week
    where('created_at < ?, date').destroy_all
	end

  def self.last_created_projects(max)
    order('created_at DESC').limit(max)
  end

  def self.firts_updated_projects(max)
    order('updated_at DESC').limit(max)
  end

  def total_hours_in_month(month,year)
    #Calculate which project entries
    #have date >= 1st month and date <= last day of month
    from = Date.new(year,month,1) #Time.new(year,month,1)
    to = from.end_of_month        #Time.new(year,month,-1)

    entries = self.entries.where(date: from..to)
    
    #Sum the hours of those entries
    total_minutes = entries.reduce(0) do |sum,entry| 
      sum + entry.hours * 60 + entry.minutes
    end

    total_hours = total_minutes / 60.0
  end
end

Day1/timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	
	def index
		@project = Project.find_by(id: params[:project_id])
		@date = Date.current

		@entries = @project.entries.where(date: @date.beginning_of_month..@date.end_of_month)
		
	end

	def new
		@project = Project.find(params[:project_id])
		#Igual que Entry.new pero de esta menera en vez de ser todos 
		#los elementos nil el project_id ya está relleno
		@entry = @project.entries.new 
	end

	def create
		#Find the project using params[:project_id]
		@project = Project.find(params[:project_id])
		
		#Create the entry project with params in params[:entry]
		@entry = @project.entries.new(entry_params)
		if @entry.save
			flash[:notice] = "Entry created successfully"
			redirect_to action: 'index', controller: 'entries', project_id: @project.id			
		else		
			flash[:alert] = "Sorry, something went wrong"
			render "new"
		end	
	end

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
	end

	def update
		#Find the project
		@project = Project.find params[:project_id]

		#Find entrey to update
		@entry = @project.entries.find params[:id]

		#update the entry using update_attributes
		if @entry.update_attributes(entry_params)
			#If ok redirect_to entries index
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		#If wrong show the form again
		else
			render "edit"
		end	
	end

	def destroy
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]

		@entry.destroy
		redirect_to action:'index', controller: 'entries', project_id: @project.id
	end


private 

	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date)
	end

end

Day1/timetracking/app/controllers/people_controller.rb
class PeopleController < ApplicationController

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(people_params)
		if @person.save
			flash[:notice] = "Person created successfully"
			redirect_to action: 'index', controller: 'people'
		else		
			flash[:alert] = "Sorry, something went wrong"
			render "new"
		end	
	end

	def index
		@person = Person.all
	end

	def show
		@person = Person.find_by(id: params[:id]) 
		@projects = @person.projects
		@projects_no_asociated = @person.select_no_associated_project 
	end

	def update
		@project = Project.find(params[:person][:projects])
		@person = Person.find(params[:id])

		@person.projects << @project
		redirect_to action: 'show', controller: 'people'
	end

	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to action:'index', controller: 'people'
	end

	private 

	def people_params
		params.require(:person).permit(:name)
	end
end

Day1/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		#@projects = Project.firts_updated_projects(10)
		@projects = Project.last_created_projects(10)
		
		if @projects.empty?
			render 'no_projects_found'
		end
	end

	def show
		@project = Project.find_by(id: params[:id]) || render_404(params)
	end

	def render_404(params)
		Rails.logger.warn("Tried to access #{params} which did not exit.")
		render "layouts/404"
	end
end

Day1/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end

	def contact
	end
end

Day1/timetracking/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_message
		display_message(:alert) || display_message(:notice)
	end

	def current_month_hours_for_project(project,date)
		project.total_hours_in_month(date.month,date.year)
	end

	private

	def display_message(type)
		if flash[type]
			content_tag :div, class: type do
				content_tag :p do
					flash[type]
				end
			end
		end
	end

end

Day1/timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

Day1/timetracking/app/helpers/people_helper.rb
module PeopleHelper
end

Day1/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

Day1/timetracking/app/helpers/site_helper.rb
module SiteHelper
end

Day1/timetracking/app/views/entries/_form.html.erb
<p><%= flash_message %></p>

<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg|%>
			<li><%= error_msg %></li>
		<% end %>		
	</ul>
<% end %>
<%= form_for [@project,@entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>

	<%= f.submit 'Save' %>
	<%= link_to('Cancel', project_entries_path(@project.id))%>
<% end %>

Day1/timetracking/app/views/entries/edit.html.erb
<h2>Updating entry in <%= @project.name %> project</h2>
<%= render 'form' %>

Day1/timetracking/app/views/entries/index.html.erb
	<% if flash[:notice] %>
		<p><%= flash[:notice] %></p>
	<% end %>
	<h1><%= @project.name %></h1>
	<ul>
		<% @entries.each do |entry| %>
			<li><%= entry.hours%>h <%= entry.minutes%>m - <%= entry.date%>
			<%= link_to('Edit', edit_project_entry_path(@project.id,entry.id)) %>
			<%= link_to('Delete',project_entry_path(@project.id,entry.id),method: 'delete', data:{confirm: 'Are you sure?'}) %></li>

		<% end %>
	</ul>
	<!--Calling a helper -->
	<p>Total hours worked this month: <%= current_month_hours_for_project(@project,@date) %></p>

<%= link_to('Go back to projects', projects_path)%>
<%= link_to('Create new entry', new_project_entry_path(@project.id))%>

Day1/timetracking/app/views/entries/new.html.erb
<h2>Creating a new entry in <%= @project.name %> project</h2>
<%= render 'form' %>

Day1/timetracking/app/views/layouts/404.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>404 - Error</title>
</head>
<body>
	<h1><strong>404</strong></h1>
	<h2>Error ! Page Not Found</h2>
	<p>For Some Reason The Page You Requested Could Not Be Found On Our Server</p>	
</body>
</html>

Day1/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<header>
			<h1>Time tracking tool</h1>
		</header>

		<%= yield %>

		<footer>
			<p>Ironhack - Rails introduction</p>
		</footer>
	</div>
</body>
</html>

Day1/timetracking/app/views/people/index.html.erb
<h2></h2>
<ul>
	<% @person.each do |person| %>
		<li>
			<%= person.name %>
			<%= link_to('Edit', person_path(person.id))%>
			<%= link_to('Delete',person_path(person.id),method: 'delete', data:{confirm: 'Are you sure?'}) %>
		</li>			
	<% end %>
</ul>
<%= link_to('Create new person', new_person_path)%>

Day1/timetracking/app/views/people/new.html.erb
<h2>Creating a new person</h2>

<p><% flash_message %></p>

<%= form_for @person do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit 'Save' %>
	<%= link_to('Cancel', people_path)%>
<% end %>

Day1/timetracking/app/views/people/show.html.erb
<h1><%= @person.name%></h1>
<h2>Projects</h2>

<ul>
		<% @projects.each do |project| %>
			<li><%= project.name %></li>
		<% end %>
</ul>	


<%= form_for [@person] do |f| %>
	<%= f.collection_select(:projects, @projects_no_asociated, :id, :name) %>
  
	<br>

	<%= f.submit 'Save' %>
	<%= link_to('Cancel', person_path)%>
<% end %>

<%= link_to('Go back to people', people_path)%>

Day1/timetracking/app/views/projects/index.html.erb
<ul>
	<% @projects.each do |project| %>
		
		<li><%= link_to(project.name, project_entries_path(project.id))%>
			<% if project.description.present? %>
			 - <%= project.description %>
			<% end %>
		</li>
	<% end %>
</ul>	

Day1/timetracking/app/views/projects/no_projects_found.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>404 - Error</title>
</head>
<body>
	<h1><strong>Error!</strong></h1>
	<h2>Array nil</h2>
	<p>Project not found</p>	
</body>
</html>

Day1/timetracking/app/views/projects/show.html.erb
	<h1><%= @project.name%></h1>
	<p><%= @project.description%></p>

Day1/timetracking/app/views/site/contact.html.erb
<p>contact@ironhack.com</p>

Day1/timetracking/app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>

<p>Ironhack powered</p>